#!/usr/bin/env bash
# rebuild-indexes.sh — Generate index.md for docs/ subdirectories using fm.sh scan-files
# Usage: rebuild-indexes.sh --project-dir <path> [--dirs rules,sops,issues]
set -euo pipefail

PROJECT_DIR=""
TARGET_DIRS=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project-dir) PROJECT_DIR="$2"; shift 2 ;;
    --dirs)        TARGET_DIRS="$2"; shift 2 ;;
    *)             echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

[[ -n "$PROJECT_DIR" ]] || { echo "Error: --project-dir is required" >&2; exit 1; }

FM_SCRIPT="$PROJECT_DIR/scripts/fm.sh"
[[ -f "$FM_SCRIPT" ]] || { echo "Error: fm.sh not found at $FM_SCRIPT" >&2; exit 1; }

TODAY=$(date +%Y-%m-%d)

# Determine directories to index
if [[ -n "$TARGET_DIRS" ]]; then
  IFS=',' read -ra DIRS <<< "$TARGET_DIRS"
else
  DIRS=()
  for d in "$PROJECT_DIR"/docs/*/; do
    [[ -d "$d" ]] || continue
    local_name=$(basename "$d")
    # Skip drafts and procs (they use fm.sh scan, not scan-files)
    case "$local_name" in
      drafts|procs) continue ;;
    esac
    DIRS+=("$local_name")
  done
fi

for subdir in "${DIRS[@]}"; do
  subdir=$(echo "$subdir" | tr -d '[:space:]')
  full_path="$PROJECT_DIR/docs/$subdir"
  [[ -d "$full_path" ]] || { echo "  skip (not found): docs/$subdir/"; continue; }

  # Check if any .md files exist (besides _template.md and index.md)
  md_count=$(find "$full_path" -maxdepth 1 -name "*.md" ! -name "_template.md" ! -name "index.md" | wc -l | tr -d ' ')
  if [[ "$md_count" -eq 0 ]]; then
    echo "  skip (no .md files): docs/$subdir/"
    continue
  fi

  # Generate TSV via fm.sh scan-files
  tsv_output=$(bash "$FM_SCRIPT" scan-files "$full_path" --fields brief,confidence,updated 2>/dev/null) || {
    echo "  skip (no frontmatter): docs/$subdir/"
    continue
  }

  # Build index.md
  index_file="$full_path/index.md"
  {
    cat <<HEADER
---
title: "Index: docs/$subdir"
doc_type: reference
brief: "Auto-generated index of docs/$subdir/ files"
confidence: verified
created: $TODAY
updated: $TODAY
revision: 1
---

# Index: docs/$subdir

| File | Brief | Confidence | Updated |
|------|-------|------------|---------|
HEADER

    while IFS=$'\t' read -r name brief confidence updated; do
      [[ -n "$name" ]] || continue
      printf '| [%s](%s.md) | %s | %s | %s |\n' "$name" "$name" "$brief" "$confidence" "$updated"
    done <<< "$tsv_output"

    printf '\n---\n*Auto-generated by rebuild-indexes.sh on %s*\n' "$TODAY"
  } > "$index_file"

  echo "  generated: docs/$subdir/index.md ($md_count files)"
done
